version: '2'
services:
  node:
    container_name: "docker-service-rabbitmq-node"
    build:
      context: ./services/node/
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - .:/srv/service
      - ./data/public:/srv/public
    ports:
      - "9977:9977"
      - "9229:9229"

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/
    ports:
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=kubide
      - RABBITMQ_DEFAULT_PASS=kubideMola