version: '2'
services:
  docker-service-rabbitmq-node:
    build:
      context: ./services/node/
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - .:/srv/service
      - ./data/public:/srv/public
    environment:
      - PROCESS=1

  docker-service-rabbitmq-node-2:
    build:
      context: ./services/node/
      dockerfile: Dockerfile
    depends_on:
      - docker-service-rabbitmq-node
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - .:/srv/service
      - ./data/public:/srv/public
    environment:
      - PROCESS=2

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/
    ports:
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=kubide
      - RABBITMQ_DEFAULT_PASS=kubideMola