version: '2'
services:
  api:
    build:
      context: ./services/api/
      dockerfile: Dockerfile
    container_name: "node-skeleton-service-container"
    depends_on:
      - database
    links:
      - database
    volumes:
      - .:/srv/service
      - ./data/public:/srv/public
    ports:
      - "9977:9977"
      - "9229:9229"

  database:
    container_name: "node-skeleton-mongodb-service-container"
    image: mongo:3
    volumes:
      - ./data/db:/data/db
    command: --storageEngine wiredTiger
    ports:
      - "27018:27017"

  cdn:
    container_name: "node-skeleton-cdn-service-container"
    build: ./services/cdn/
    volumes:
      - ./data/public:/usr/share/nginx/cdn
    ports:
      - "8080:80"
